[package]
name = "test_final_verification"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "test_final_verification"
path = "src/main.rs"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
